name: bank_churn_classification
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.13.2
  - cycler=0.11.0
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fonttools=4.55.3
  - freetype=2.12.1
  - glib=2.82.2
  - glib-tools=2.82.2
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - icu=75.1
  - importlib-metadata=8.6.1
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=9.0.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=19.1.7
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libzlib=1.3.1
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - nest-asyncio=1.6.0
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.3
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.13
  - pywin32=307
  - pyzmq=26.2.1
  - qt-main=5.15.15
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - setuptools=75.8.2
  - sip=6.7.12
  - six=1.17.0
  - sqlite=3.49.1
  - stack_data=0.6.3
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - pytz==2025.1
